export const EMAIL = "hello@damiisdandy.com"
export const GITHUB = "https://github.com/damiisdandy"
export const TWITTER = "https://twitter.com/realdamiisdandy"
export const CALENDLY = "https://calendly.com/damiisdandy/get-to-know-me-1"
export const SPOTIFY_PLAYLIST_ID = "37i9dQZF1EVHGWrwldPRtj"